import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import { Toaster } from "@/components/ui/toaster";
import { cookies } from "next/headers";
import { db } from "@/lib/db";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const token = cookieStore.get("auth-token")?.value;

  const admin = token
    ? await db.profile.findFirst({
      where: {
        token: token,
        role: "ADMIN",
      },
    }) : null;

  return (
    <html lang="en">
      <body>
          <NavBar/>
          <main>
            {children}
            <Toaster />
          </main>
          <Footer />
      </body>
    </html>
  );
}
